services:
  php_recettes:
    build: ./php-service
    ports:
      - "${PHP_PORT}:80"
    env_file:
      - ./php-service/.env
    depends_on:
      - mongodb

  express_utilisateurs:
    build: ./express-service
    ports:
      - "${EXPRESS_PORT}:3000"
    env_file:
      - ./express-service/.env
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: mongo_db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    volumes:
      - mongo_data:/data/db
    ports:
      - "27018:${MONGO_PORT}"

  web_interface:
    build: ./frontend
    ports:
      - "${FRONTEND_PORT}:80"
    depends_on:
      - php_recettes
      - express_utilisateurs

volumes:
  mongo_data:
